name: creating_docker_img

on: workflow_dispatch

jobs:
  perform_creation_of_image:
    runs-on: ubuntu-latest

    steps:

    - name: config git and delete old update_modules branch
      continue-on-error: true
      run: |
        git config --global user.name "marcelmmc"
        git config --global user.email marcel.morancalderon@epfl.ch
        git config --global user.token ${{ secrets.CELMARBOT2 }}
        git clone git@github.com:marcelmmc/data_reports.git
        ls -a
      env:
          GITHUB_TOKEN: ${{ secrets.CELMARBOT2 }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      #
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      #
      #
      #
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: "{{defaultContext}}:creating_docker_image"
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/dockerms3:testimg
