name: creating_docker_img
on: workflow_dispatch
jobs:
  perform_creation_of_image:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout main
      uses: actions/checkout@v3
      with:
        repository: marcelmmc/data_reports
        ref: romantic_corpus
        path: data_reports
        token: ${{ secrets.BOTSECRETCELM }}

    - name: Checkout main
      uses: actions/checkout@v3
      with:
        path: main
        token: ${{ secrets.BOTSECRETCELM }}

    - name: config git and delete old update_modules branch
      continue-on-error: true
      run: |
        ls -a
        cp -r data_reports main/
        cd main
        ls -a


      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      #
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      #
      #
      #
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: "{{defaultContext}}:creating_docker_image"
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/dockerms3:testimg
