name: creating_docker_img
on: workflow_dispatch
jobs:
  perform_creation_of_image:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout main
      uses: actions/checkout@v3
      with:
        repository: marcelmmc/data_reports
        ref: romantic_corpus
        path: data_reports
        token: ${{ secrets.BOTSECRETCELM }}

    - name: Checkout main
      uses: actions/checkout@v3
      with:
        path: main
        token: ${{ secrets.BOTSECRETCELM }}

    - name: create tag
      uses: negz/create-tag@v1
      continue-on-error: true
      with:
        version: "v1.2.5"
        message: "v1.2.5"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check if pull
      id: checkpull
      working-directory: ./main
      continue-on-error: true
      run: |
        gh api --method PATCH -H "Accept: application/vnd.github+json" repos/marcelmmc/dcml_corpus_workflow/releases/92046324 -f tag_name='1.2.5' -f target_commitish='main' -f name='1.2.4' -f body='Description of the release' -F draft=false -F prerelease=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: config git and delete old update_modules branch
      continue-on-error: true
      run: |
        ls -a
        cp -r data_reports main/creating_docker_image
        ls -a

    # - name: transform py or md to notebook
    #   working-directory: main/creating_docker_image/data_reports
    #   continue-on-error: true
    #   run: |
    #     ls -a
    #     pip install jupytext
    #     jupytext --to notebook generate.py
    #     jupytext --to notebook notes_stats.py
    #     ls -a
    #
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    #
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Build and push
    #   uses: docker/build-push-action@v4
    #   with:
    #     # context: "{{defaultContext}}:creating_docker_image"
    #     context: "${{ github.workspace }}/main/creating_docker_image"
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/dockerms3:testimg
