name: publish pages
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.name }}
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Init new repo in dist folder and commit generated files
      run: |
        mkdir pages
        ls -a
        cd pages
        cp "${{ github.workspace }}/${{ github.event.repository.name }}/pages/*" .
        ls -a
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'

    # - name: simple action
    #   uses: marcelmmc/dcml_corpus_workflow@v2.0.1-ms3-1.2.3-dimcat-0.3.0-data_reports-a79ac75
    #   env:
    #     directory: "${{ github.workspace }}"
    #     working_dir: ${{ github.event.repository.name }}
    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./pages

    #     ls -a
