name: test tag release
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tag Repoo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: 1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
