# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
name: publish branchxx
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3.0.1
