name: test_sphinx

on:
  push:

jobs:
  generate_and_publish:
    if: >
    runs-on: ubuntu-latest
    steps:


    - name: Checkout corpus_docs repository
      uses: actions/checkout@v3
      with:
        repository: 'DCMLab/corpus_docs'
        fetch-depth: 0
        submodules: true
        token: ${{ secrets.CELMARBOT2 }}
        path: corpus_docs

    # - name: Download dimcat repository, install dependecies and pull notebooks
    #   continue-on-error: false
    #   run: |
    #     cd corpus_docs
    #     git submodule update --init --recursive

    - name: Checkout corpus repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.CELMARBOT2 }}
        path: ${{ github.event.repository.name }}

    - name: Testing repo
      continue-on-error: false
      run: |
        git clone https://github.com/DCMLab/tchaikovsky_seasons.git

    - name: Start sphinx
      continue-on-error: false
      run: |
        pip install Sphinx
        cd corpus_docs/notebooks
        ls -a
        # export CORPUS_PATH="${{ github.workspace }}/${{ github.event.repository.name }}"
        export CORPUS_PATH="${{ github.workspace }}/tchaikovsky_seasons"
        echo "$CORPUS_PATH"
        ipython kernel install --name "ms3" --user
        ipython kernel install --name "dimcat" --user
        make html
        ls -a
        sudo mv _build/html ../../pages
        cd ../../
        ls -a
        cd pages
        ls -a
        cd notebooks
        ls -a


    - name: Check pages are generated
      continue-on-error: false
      run: |
        if [[ -f ./pages/notebooks/generate.html ]] && [[ -f ./pages/notebooks/notes_stats.html ]]; then
          echo "Pages generated"
        else
          echo "There was a problem generating pages"
          exit 1
        fi

    - name: Switch or create a gh-pages branch
      continue-on-error: true
      run: |
        cd ${{ github.event.repository.name }}
        git branch --all
        exist=$(echo $(git branch --all | grep "gh-pages"))
        if [[ -z "$exist" ]]; then
          git checkout -b gh-pages
          git push --set-upstream origin gh-pages
        else
          git checkout gh-pages
        fi

    - name: Add files to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./pages
        enable_jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.CELMARBOT2 }}

    # - name: Add files to gh-pages
    #   run: |
    #     cd ${{ github.event.repository.name }}
    #     shopt -s extglob
    #     sudo rm -rf *
    #     if [[ -f .github/workflows ]]; then
    #       sudo rm -rf .github/workflows
    #     fi
    #     cp -r ../pages/* .
    #     echo "" > .nojekyll
    #     git config --local user.email "marcel.morancalderon@epfl.ch"
    #     git config --local user.name "marcelmmc"
    #     git config --global user.token ${{ secrets.CELMARBOT2 }}
    #     git config --global --add safe.directory "${{ github.workspace }}/${{ github.event.repository.name }}"
    #     git add .
    #     git commit -m "deploy"
    #     git push
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.CELMARBOT2 }}
