name: test tag release
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Release Tag Updater
      uses: sersoft-gmbh/running-release-tags-action@v2
      with:
        tag: 1.2.3
