name: test action
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        path: main
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: transform py or md to notebook
      continue-on-error: true
      run: |
        cd "$GITHUB_WORKSPACE/main/testPath/tchaikovsky_seasons"
        ls -a
    # - name: simple action
    #   uses: marcelmmc/dcml_corpus_workflow@v1.9.5-ms3-1.2.3-dimcat-0.3.0-data_reports-236344a
    # env:
    #   PATH_TO_REPO: ${{ $GITHUB_WORKSPACE }}/main/testPath/beethoven_piano_sonatas
