name: test action
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.name }}
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}


    - name: simple action
      uses: marcelmmc/dcml_corpus_workflow@v1.9.7-ms3-1.2.3-dimcat-0.3.0-data_reports-236344a
      env:
        directory: "${{ github.workspace }}"
        working_dir: ${{ github.event.repository.name }}


    - name: check path exists
      continue-on-error: true
      run: |
        cd "$PATH_TO_REPO"
        ls -a
